### ISSUE TITLE
SQS Messages are not decoded from base64

### ISSUE THREAD

**Issue by gautamk** [logstash-plugins/logstash-input-sqs#15]
The default AWS library boto encodes messages into base64 before putting them on SQS.
The SQS messages are not decoded in logstash. 

http://boto.readthedocs.org/en/latest/ref/sqs.html#boto.sqs.message.Message

**Comment by ph** [comment]
@gautamk boto encode the body of the message in base64? If it is the case this behavior should be implemented as a codec and the sqs input could use it.

**Comment by ph** [comment]
@gautamk until we add a codec to decode base64 message you can use the ruby filter and some ruby code to do it, make sure you use the plain text codec for the sqs input.

This should work, but I haven't tested it.

```
filter {
    ruby { 
            init=> "require 'base64'"
            code => "event['message'] = Base64.decode64(event['message'])"
     }
}
```

**Comment by kares** [comment]
this issue seems to be stale/defuncts, closing
