### ISSUE TITLE
Support for us-east-2?

### ISSUE THREAD

**Issue by gjahn000** [logstash-plugins/logstash-input-sqs#39]
Any plans to support us-east-2? Should region list additions be configurable?

input {
    sqs {
      # This setting must be a ["us-east-1", "us-west-1", "us-west-2", "eu-central-1", "eu-west-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "ap-northeast-2", "sa-east-1", "us-gov-west-1", "cn-north-1", "ap-south-1"]
      # Expected one of ["us-east-1", "us-west-1", "us-west-2", "eu-central-1", "eu-west-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "ap-northeast-2", "sa-east-1", "us-gov-west-1", "cn-north-1", "ap-south-1"], got ["us-east-2"]
      region => "us-east-2"

**Comment by jsvd** [comment]
please follow https://github.com/logstash-plugins/logstash-mixin-aws/pull/36 as it will be solved there
