### ISSUE TITLE
ap-south-1 is not a valid region

### ISSUE THREAD

**Issue by ANIL1311** [logstash-plugins/logstash-input-sqs#41]
I have configured glacier in centos 7 and after making necessary changes in ./glacier-cmd I'm getting an error by stating 
str: Invalid region. Available regions for Amazon Glacier are:
us-east-1 (US - Virginia)
us-west-1 (US - N. California)
us-west-2 (US - Oregon)
eu-west-1 (EU - Ireland)
eu-central-1 (EU - Frankfurt)
sa-east-1 (South America - Sao Paulo)
ap-northeast-1 (Asia-Pacific - Tokyo)
ap-southeast-1 (Asia Pacific (Singapore)
ap-southeast-2 (Asia-Pacific - Sydney)
Caused by: 1 exception
||  str: Invalid region code: ap-south-1

**Comment by jsvd** [comment]
please follow pr https://github.com/logstash-plugins/logstash-mixin-aws/pull/36 as this should be solved there
