### ISSUE TITLE
When messages get deleted from the sqs queue ? 

### ISSUE THREAD

**Issue by dtuyenle** [logstash-plugins/logstash-input-sqs#54]
When messages get deleted from the sqs queue ? or it never using this plugin ?

**Comment by kares** [comment]
as per the official SDK [docs](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/SQS/QueuePoller.html) messages are automatically deleted when the event is processed.
please use LS [forums](https://discuss.elastic.co/c/elastic-stack/logstash) of SO if you have questions, the issues here are for plugin issues.
