### ISSUE TITLE
Improve Debug Logging

### ISSUE THREAD

**Issue by robbavey** [logstash-plugins/logstash-input-sqs#59]
Determining the source of any connection errors in this plugin is tricky, due to the lack of debugging in the plugin, with little to no debug logging to understand where issues are happening. 

As well as a lack of plugin level logging, this plugin does not provide any ability to provide wire level tracing via passing `additional_settings` through to the underlying library that is used to connected to `SQS` - see https://www.elastic.co/guide/en/logstash/current/plugins-inputs-s3.html#plugins-inputs-s3-additional_settings for an example.

By including `additional_settings`, the user is able to change the log level of the AWS SDK, and also set `http_wire_trace` to track the requests to/from AWS. See https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/SQS/Client.html#initialize-instance_method for details of applicable `additional_settings`

**Comment by andsel** [comment]
Fixed with `v3.3.0`
