### ISSUE TITLE
plugin stops polling on various exceptions

### ISSUE THREAD

**Issue by algesten** [logstash-plugins/logstash-input-sqs#6]
Two times lately, our connection to SQS was interrupted. First was due to connectivity error, second time due to an internal error at Amazon.

The exception first time is lost.

However the second time we get:

```
{:timestamp=>"2015-04-23T11:22:07.605000+0200", :message=>"Error reading SQS queue.", :error=>#<AWS::Errors::Base: <ServiceUnavailableException/>
>, :queue=>"sqs-transcoder", :level=>:error}
```

Suggest doing retries also on non-specific errors that ends up here: https://github.com/logstash-plugins/logstash-input-sqs/blob/master/lib/logstash/inputs/sqs.rb#L170

**Comment by ph** [comment]
1.1.0 includes that fixes and will keep retrying using a backoff strategy.
