### ISSUE TITLE
Logstash SQS too slow to process

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-sqs#8]
(This issue was originally filed by @PraveenJayakrishnakumar at https://github.com/elastic/logstash/issues/2515)

---

I observed that logstash SQS input queue is making too slow to process the logs and sometimes it breaks the process, if it processing more log messages.

Following error messages am getting when it started to process more logs,
1. Errno::EBADF: Bad file descriptor - Bad file descriptor
2. AWS::SQS::Errors::SignatureDoesNotMatch
3. AWS::SQS::Errors::BatchRequestTooLong
4. AWS::SQS::Errors::ChecksumError

**Comment by arabold** [comment]
I've observed slowness (I'm on single-thread but will switch to multi-threading now) but never any of those errors with Logstash 1.4.2. Logstash 1.5.0 cannot be used due to other errors in the grok parser that make it fail and crash badly.

**Comment by ph** [comment]
But the way the SQS library works (at least in ruby) is a poll model, the client connect to the HTTP server and request batch of SQS messages, the maximum of fetched messages is **10** per call. The way to make it scale is to use the `threads` option for this input to have more workers calling the same SQS endpoint which would result in higher throughput, because the bottle neck is mostly due to IO.

The number of threads depends on your server capacity and you may want to experiment with that number. To give you some numbers, I was able to do 400 events per second on my macbook.

Example:

```
input {
sqs {
[other options]
threads => 20
}
```

**Comment by ph** [comment]
Also concerning the `AWS` errors, the PR #18 uses the version 2 of the API and I think it will resolve some of these issues.

**Comment by ph** [comment]
@arabold Concerning the grok issues did you report them in the grok repository? https://github.com/logstash-plugins/logstash-filter-grok

**Comment by arabold** [comment]
@ph, I appreciate your time. Those grok issues have been addressed in the meantime. I'm using Logstash 1.5.3 with SQS as my primary queue (instead of Redis for example) in semi-production now. No performance data but I'm satisfied with the results since enabling multiple threads.

**Comment by ph** [comment]
@arabold Awesome, I should release a new version soon of the SQS input since the current version has a memory leak that can reduce the performance of logstash after a few hours (depending on the load)

**Comment by ph** [comment]
I've released the SQS input 1.1.0 that should give a bit more throughput, I don't have numbers yet.
But you have now two way to tweak it:
1. Use multiples threads
2. use a lower values for `polling_frequency`, we use the default value of SQS which is 20 seconds between each polling.

Also v2 version of the api have added a lot of retry logic that should deal with most of the `ChecksumError`, `SignatureDoesNotMatch`

**Comment by arabold** [comment]
Thanks for the update. I'm testing it right now.
