### ISSUE TITLE
Error reading SQS queue

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-sqs#9]
(This issue was originally filed by @PraveenJayakrishnakumar at https://github.com/elastic/logstash/issues/2190)

---

We are using logstash indexer to read all logs from logstash-agent. But, sometime, we are getting checksum failed error. we are using logstash verion 1.4.3

:message=>"Error reading SQS queue.", :error=>#&lt;AWS::SQS::Errors::ChecksumError: 2 messages failed checksum verification&gt;,

**Comment by rlister** [comment]
Seeing same issue on 1.5.0. Something of a show-stopper for us right now.

**Comment by JonathanSerafini** [comment]
To get around this issue, I temporarily disabled checksum verification in lib/logstash/inputs/sqs.rb
101     @sqs = AWS::SQS.new(aws_options_hash.merge(:sqs_verify_checksums => false)

**Comment by PraveenJayakrishnakumar** [comment]
Thanks for your response, Like you said, it is just workaround. But, We are looking for the permanent solution in production box.

**Comment by rlister** [comment]
@JonathanSerafini Thanks for the workaround. If anyone is interested, I've forked this gem to https://github.com/rlister/logstash-input-sqs, applied the workaround (set env var `SQS_SKIP_CHECKSUMS`) and created a docker image, which can be run something like this:

```
docker run -d -e SQS_SKIP_CHECKSUMS=true rlister/logstash:1.5.0-sqs-hack agent -e 'input { sqs { queue => "logstash" } } output { stdout {} }'
```

**Comment by cdenneen** [comment]
Can this get fixed in 1.4 branch (1.4.4 maybe) as a backport maybe as well as 1.5?

**Comment by cdenneen** [comment]
Also the issue I think is not just checksum's but any sort of issue... (plugin doesn't restart as expected just dies)

{:timestamp=>"2015-06-11T16:27:43.449000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}

We've seen this when the queue has like 1M messages the timeout happens.

I have 8 threads on the SQS input and looking through the log you can watch them all die:

```
{:timestamp=>"2015-06-11T12:53:22.236000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:05:04.023000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:10:38.453000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:19:27.005000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:22:55.558000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:25:58.123000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:41:36.046000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
{:timestamp=>"2015-06-11T13:55:24.643000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"int-LogQueue", :level=>:error}
```

**Comment by JonathanSerafini** [comment]
Ah well that there is a separate issue .. Timeout::Error exception ends run_with_backoff and therefore ends run... Logstash 1.4 expects the run method to run forever, so the input plugin will simply die. Pretty sure that behavior has changed in Logstash 1.5.

**Comment by cdenneen** [comment]
other plugins like s3 restart, is there a reason this wouldn't do the same? it's getting an error which should trigger a restart of some sort no? #14 opened

**Comment by JonathanSerafini** [comment]
Well what I meant is that you're getting a different exception than the initial thread which needs to be resolved differently. Specifically, you'd likely want to put a dedicated rescue for Timeout exceptions around https://github.com/logstash-plugins/logstash-input-sqs/blob/master/lib/logstash/inputs/sqs.rb#L170.

**Comment by ph** [comment]
We have changed how we are doing the polling of SQS, we rely on the `QueuePoller` from AWS library instead of using our own strategy. Also the library will now retry on checksum error so I think its safe to close this issue. Please upgrade the plugin to 1.1.0, if this issue still happen please open a new issue.

**Comment by cdenneen** [comment]
@ph is this in 1.5.4?

```
[root@lsbroker02 logstash]# tail logstash.log
{:timestamp=>"2015-08-28T13:07:02.262000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"logstash-prod-inputqueue", :level=>:error}
{:timestamp=>"2015-08-28T13:10:26.103000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"logstash-prod-inputqueue", :level=>:error}
{:timestamp=>"2015-08-28T13:30:56.767000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"logstash-prod-inputqueue", :level=>:error}
{:timestamp=>"2015-08-28T13:31:41.325000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"logstash-prod-inputqueue", :level=>:error}
{:timestamp=>"2015-08-28T13:45:19.566000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"logstash-prod-inputqueue", :level=>:error}
{:timestamp=>"2015-08-28T13:46:54.037000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"logstash-prod-inputqueue", :level=>:error}
{:timestamp=>"2015-08-28T14:09:46.355000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"logstash-prod-inputqueue", :level=>:error}
{:timestamp=>"2015-08-28T16:48:45.496000-0400", :message=>"Error reading SQS queue.", :error=>#<Timeout::Error: execution expired>, :queue=>"logstash-prod-inputqueue", :level=>:error}

[root@lsbroker02 logstash]# /opt/logstash/bin/logstash -V
logstash 1.5.4
```

logstash process died (as you see all 8 threads for input died) and nothing in logstash.err

**Comment by cdenneen** [comment]
@ph i see plugin was updated to 1.1.0 so I updated that manually vs waiting for 1.5.5 ;) (will see if that works)
Is there anyway @jordansissel we can have plugin display version? or display current vs latest? will plugin update without plugin name upgrade all plugins?

**Comment by JonathanSerafini** [comment]
I think plugin is wrapping around standard bundle / gem workflow so you ought to be able to see the plugin version in the Gemfile.jruby-1.9.lock in the root of your logstash installation. Really not altogether sure that doing an update of all the plugins would be entirely safe, if atleast they used semantic versioning or something ...

**Comment by cdenneen** [comment]
@JonathanSerafini Yeah can do a 'find /opt/logstash -name _sqs_' too to find version but not sure that's best way

**Comment by ph** [comment]
@cdenneen a bit late, but you can do `bin/plugin list --verbose sqs` and this  will give you the installed version.
